[package]
name = "rubarc"
version = "0.1.0"
authors = ["jrgriffin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
imageproc = "0.21.0"
